#!/bin/bash
# Set hostname
if [ -z $1 ]; then
    echo "No hostname provided"
    exit
fi
sudo hostnamectl hostname $1

sudo apt install --assume-yes software-properties-common
sudo apt-add-repository --yes --component non-free
sudo apt-add-repository --yes --component contrib

sudo apt-get update
sudo apt-get --assume-yes upgrade
sudo apt-get --assume-yes install $(cat ./pkgs)

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo flatpak remote-modify --enable flathub

# Copy system config files
sudo rsync -rv ./system/ /

if [ "$1" == "ultra24" ]; then
    sudo systemctl enable var-mnt-data.mount
fi

git clone https://github.com/ValveSoftware/steam-devices /tmp/steam-devices
sudo cp /tmp/steam-devices/*.rules /etc/udev/rules.d/.
rm -rf /tmp/steam-devices
